title: Megan Andersen Personal Website
description: website created 16NOV2025
theme: jekyll-theme-cayman
# Or use: jekyll-theme-cayman, jekyll-theme-slate, etc.
header_pages:
  - index.md
  - about.md
  - research.md
